<script>
    export let form;
    </script>

    <div class="agn-card elevated">
        <div class="agn-stack gap-5">

                <div class="agn-stack gap-2" style="text-align: center;">
                            <h1>Buat Akun</h1>
                                        <p class="is-muted">Gabung dan mulai berbagi.</p>
                                                </div>

                                                        <form method="POST" class="agn-stack gap-4">

                                                                    <div class="agn-input-group">
                                                                                    <label class="agn-input-label">Username</label>
                                                                                                    <input
                                                                                                                        class="agn-input {form?.errors?.username ? 'is-error' : ''}"
                                                                                                                                            type="text"
                                                                                                                                                                name="username"
                                                                                                                                                                                    required
                                                                                                                                                                                                    />
                                                                                                                                                                                                                    {#if form?.errors?.username}
                                                                                                                                                                                                                                        <span class="agn-input-error">{form.errors.username}</span>
                                                                                                                                                                                                                                                        {/if}
                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                <div class="agn-input-group">
                                                                                                                                                                                                                                                                                                <label class="agn-input-label">Email</label>
                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                    class="agn-input {form?.errors?.email ? 'is-error' : ''}"
                                                                                                                                                                                                                                                                                                                                                        type="email"
                                                                                                                                                                                                                                                                                                                                                                            name="email"
                                                                                                                                                                                                                                                                                                                                                                                                required
                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                {#if form?.errors?.email}
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span class="agn-input-error">{form.errors.email}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/if}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="agn-input-group">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <label class="agn-input-label">Password</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                class="agn-input {form?.errors?.password ? 'is-error' : ''}"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        name="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {#if form?.errors?.password}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span class="agn-input-error">{form.errors.password}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/if}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button class="agn-btn full-width" data-variant="primary">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Daftar
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </form>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <hr class="agn-divider" />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style="text-align: center;">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span class="is-muted">Sudah punya akun?</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a href="/auth/login"> Masuk</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
